"""adding title, price and category to job

Revision ID: a16c389fabb9
Revises: 44a417f290e0
Create Date: 2024-02-01 14:54:10.665442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16c389fabb9'
down_revision = '44a417f290e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=25), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('price')
        batch_op.drop_column('title')

    # ### end Alembic commands ###