"""changed default value for worker_id to 0

Revision ID: 9dc68f021865
Revises: 42e7162feae2
Create Date: 2024-02-01 18:56:09.514159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc68f021865'
down_revision = '42e7162feae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('worker_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('worker_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###